package com.neoSoft.misc;

public enum NotificationTypes {

	ROOM_BOOK_REQUEST,
	ROOM_BOOK_RESPONSE,
	USER_REGISTRATION_REQUEST,
	FEEDBACK_SENT,
	CHANGE_MAIL_REQUEST,
	CHANGE_MAIL_RESPONSE,
	CHANGE_DEPT_REQUEST,
	CHANGE_DEPT_RESPONSE;
	
	
}
